### ISSUE TITLE
unexpected reloc type 0x03

### ISSUE THREAD

**Issue by BraindeadBZH** [BareConductive/wiringpi-mpr121#2]
Hello,

I'm trying this lib to access  a capacitive num pad. I wrote a very basic program

```c++
#include <stdio.h>
#include <wiringPi.h>
#include <MPR121.h>

#define KEYPAD_ADDR 0x5B

int main(void)
{
  wiringPiSetup();

  printf("Test Capacitive Touch Num Pad\n");

  MPR121.begin(KEYPAD_ADDR);

  return 0;
}
```

I compile it with no issue with the following command:
` g++ -lwiringPi -lMPR121 -o capacitive capacitive.c`

But I get the following error when I run it:

> error while loading shared libraries: /usr/lib/libMPR121.so: unexpected reloc type 0x03

I also tried this compile command without success:
`g++ -Wl,-Bsymbolic -lwiringPi -lMPR121 -o capacitive capacitive.c`

**Comment by stefandz** [comment]
A quick bit of work on DuckDuckGo got me this: https://stackoverflow.com/questions/33474070/unexpected-reloc-type-0x03

Try again with `g++ -lwiringPi -lMPR121 -fPIC -o capacitive capacitive.c`

**Comment by BraindeadBZH** [comment]
Sorry forgot to mention that I also tried this, with the same result. I also tried to remove -fPIC while compiling wiringPi and wiringpi-mpr121, with no luck.

I'm running an Arch Linux ARM 32Bit.

**Comment by stefandz** [comment]
This library has been built and tested on Raspbian running on all the currently available Raspberry Pi models. While it should work on Arch Linux running on whatever processor you have, it is possible that there will be issues (as you have identified). We don't have any systems here running Arch Linux that we can use for testing. What CPU are you running on? My best advice would be to try running `g++ -lwiringPi -lMPR121 -wall -v -Wl,-v -o capacitive capacitive.c` to enable verbose output from both GCC and the linker and seeing if that points you in the right direction. You could equally try adding the same flags to your original compilation of the wiringpi-mpr121 lib and wiringpi itself to see if there are any warnings or obvious issues there.

If you find something that can fix this issue, let me know or drop us a pull request and I can include it so that other people can benefit.
